### ISSUE TITLE
inkscape 0.91

### ISSUE THREAD

**Issue by meirm** [ringo2k/laserengraverInkscapeplugin#1]
worked great in previous versions of inkscape.

Traceback (most recent call last):
  File "laserengraver.py", line 3188, in <module>
    e.affect()  
  File "/usr/share/inkscape/extensions/inkex.py", line 268, in affect
    self.effect()
  File "laserengraver.py", line 3156, in effect
    self.orientation( self.layers[min(0,len(self.layers)-1)] )  
  File "laserengraver.py", line 3080, in orientation
    doc_height = inkex.unittouu(self.document.getroot().get('height'))
AttributeError: 'module' object has no attribute 'unittouu'

File "laserengraver.py", line 3188, in <module>

e.affect()

File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect

self.effect()

File "laserengraver.py", line 3156, in effect

self.orientation( self.layers[min(0,len(self.layers)-1)] )

File "laserengraver.py", line 3080, in orientation

doc_height = inkex.unittouu(self.document.getroot().get('height'))

AttributeError: 'module' object has no attribute 'unittouu'

**Comment by meirm** [comment]
fixed very simple:
replace line 3080 of laserengraver.py for:
doc_height = self.unittouu(self.document.getroot().get('height'))

**Comment by ringo2k** [comment]
thanks! when i upgrade my inkscape i will check this.

**Comment by caoxiangfish** [comment]
@meirm 
replace line 3103 of laserengraver.py for:
doc_height = self.unittouu(self.document.getroot().get('height'))

**Comment by 1wise** [comment]
I needed to change this too
orientation_scale line
        if self.options.unit == "G21 (All units in mm)" : 
            points = [[0.,0.,0.],[100.,0.,0.],[0.,100.,0.]]
            orientation_scale = 1
